export const dummyAffiliateData = [
  {
    affiliate: "Affiliate X",
    date: "2024-08-01",
    linksShared: 10,
    occupation: "Student",
    productsMarketed: ["Product A", "Product B"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-03",
    linksShared: 12,
    occupation: "Student",
    productsMarketed: ["Product A", "Product C"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-05",
    linksShared: 14,
    occupation: "Professional",
    productsMarketed: ["Product D", "Product E"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-07",
    linksShared: 16,
    occupation: "Professional",
    productsMarketed: ["Product F", "Product G"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-09",
    linksShared: 18,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product H", "Product I"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-11",
    linksShared: 17,
    occupation: "Marketing Agent",
    productsMarketed: ["Product J", "Product K"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-13",
    linksShared: 15,
    occupation: "Teacher",
    productsMarketed: ["Product L", "Product M"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-15",
    linksShared: 16,
    occupation: "Placement Officer",
    productsMarketed: ["Product N", "Product O"],
  },
  {
    affiliate: "Affiliate X",
    date: "2024-08-17",
    linksShared: 18,
    occupation: "Other",
    productsMarketed: ["Product P", "Product Q"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-02",
    linksShared: 15,
    occupation: "Professional",
    productsMarketed: ["Product R", "Product S"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-04",
    linksShared: 17,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product T", "Product U"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-06",
    linksShared: 19,
    occupation: "Marketing Agent",
    productsMarketed: ["Product V", "Product W"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-08",
    linksShared: 21,
    occupation: "Teacher",
    productsMarketed: ["Product X", "Product Y"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-10",
    linksShared: 23,
    occupation: "Placement Officer",
    productsMarketed: ["Product Z", "Product A1"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-12",
    linksShared: 22,
    occupation: "Other",
    productsMarketed: ["Product B1", "Product C1"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-14",
    linksShared: 20,
    occupation: "Student",
    productsMarketed: ["Product D1", "Product E1"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-16",
    linksShared: 21,
    occupation: "Professional",
    productsMarketed: ["Product F1", "Product G1"],
  },
  {
    affiliate: "Affiliate Y",
    date: "2024-08-18",
    linksShared: 23,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product H1", "Product I1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-03",
    linksShared: 8,
    occupation: "Marketing Agent",
    productsMarketed: ["Product J1", "Product K1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-05",
    linksShared: 9,
    occupation: "Teacher",
    productsMarketed: ["Product L1", "Product M1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-07",
    linksShared: 10,
    occupation: "Placement Officer",
    productsMarketed: ["Product N1", "Product O1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-09",
    linksShared: 11,
    occupation: "Other",
    productsMarketed: ["Product P1", "Product Q1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-11",
    linksShared: 10,
    occupation: "Student",
    productsMarketed: ["Product R1", "Product S1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-13",
    linksShared: 9,
    occupation: "Professional",
    productsMarketed: ["Product T1", "Product U1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-15",
    linksShared: 10,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product V1", "Product W1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-17",
    linksShared: 11,
    occupation: "Marketing Agent",
    productsMarketed: ["Product X1", "Product Y1"],
  },
  {
    affiliate: "Affiliate Z",
    date: "2024-08-19",
    linksShared: 12,
    occupation: "Teacher",
    productsMarketed: ["Product Z1", "Product A2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-04",
    linksShared: 20,
    occupation: "Placement Officer",
    productsMarketed: ["Product B2", "Product C2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-06",
    linksShared: 22,
    occupation: "Other",
    productsMarketed: ["Product D2", "Product E2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-08",
    linksShared: 24,
    occupation: "Student",
    productsMarketed: ["Product F2", "Product G2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-10",
    linksShared: 26,
    occupation: "Professional",
    productsMarketed: ["Product H2", "Product I2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-12",
    linksShared: 25,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product J2", "Product K2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-14",
    linksShared: 23,
    occupation: "Marketing Agent",
    productsMarketed: ["Product L2", "Product M2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-16",
    linksShared: 24,
    occupation: "Teacher",
    productsMarketed: ["Product N2", "Product O2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-18",
    linksShared: 26,
    occupation: "Placement Officer",
    productsMarketed: ["Product P2", "Product Q2"],
  },
  {
    affiliate: "Affiliate W",
    date: "2024-08-20",
    linksShared: 28,
    occupation: "Other",
    productsMarketed: ["Product R2", "Product S2"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-05",
    linksShared: 5,
    occupation: "Student",
    productsMarketed: ["Product T2", "Product U2"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-07",
    linksShared: 6,
    occupation: "Professional",
    productsMarketed: ["Product V2", "Product W2"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-09",
    linksShared: 7,
    occupation: "Social Media Influencer",
    productsMarketed: ["Product X2", "Product Y2"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-11",
    linksShared: 8,
    occupation: "Marketing Agent",
    productsMarketed: ["Product Z2", "Product A3"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-13",
    linksShared: 7,
    occupation: "Teacher",
    productsMarketed: ["Product B3", "Product C3"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-15",
    linksShared: 6,
    occupation: "Placement Officer",
    productsMarketed: ["Product D3", "Product E3"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-17",
    linksShared: 7,
    occupation: "Other",
    productsMarketed: ["Product F3", "Product G3"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-19",
    linksShared: 8,
    occupation: "Student",
    productsMarketed: ["Product H3", "Product I3"],
  },
  {
    affiliate: "Affiliate V",
    date: "2024-08-21",
    linksShared: 9,
    occupation: "Professional",
    productsMarketed: ["Product J3", "Product K3"],
  },
];
